stages:
  - build
  - deploy

# Build job (optional if you have assets to compile)
build-job:
  image: node:lts
  stage: build
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - npm run build

deploy-job:
  image: node:lts
  stage: deploy
  environment: production
  script:
    - npm install -g firebase-tools
    - npm install
    - npm run build
    - echo "$GOOGLE_APPLICATION_CREDENTIALS" > /tmp/key.json
    - export GOOGLE_APPLICATION_CREDENTIALS="/tmp/key.json"
    - firebase deploy --project e-commerce-project-e24b8
  only:
    - main
